// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['paper'], function(paper) {
  var Chain;
  Chain = (function() {

    function Chain(canvas) {
      this.mouse_up = __bind(this.mouse_up, this);

      this.mouse_move = __bind(this.mouse_move, this);

      this.mouse_down = __bind(this.mouse_down, this);

      this.init = __bind(this.init, this);

      var self;
      this.canvas = canvas;
      this.paper = new paper.PaperScope();
      this.paper.setup(this.canvas);
      this.tool = new this.paper.Tool();
      this.path = new paper.Path();
      this.size = 25;
      this.segments = this.path.segments;
      this.style = {
        strokeColor: "gray",
        strokeWidth: 15,
        strokeCap: "round"
      };
      this.path.style = this.style;
      this.init();
      self = this;
      this.tool.onMouseDown = function(event) {
        return self.mouse_down(event);
      };
      this.tool.onMouseMove = function(event) {
        return self.mouse_move(event);
      };
      this.tool.onMouseUp = function(event) {
        return self.mouse_up(event);
      };
    }

    Chain.prototype.init = function() {
      var i, start, _i, _ref;
      start = this.paper.view.center;
      for (i = _i = 0, _ref = this.size; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.path.add(new this.paper.Point(start.x + i * 10, start.y));
      }
      this.paper.view.draw();
      return this.tool.onMouseDown = this.paper.onMouseDown;
    };

    Chain.prototype.mouse_down = function(event) {
      this.path.style = {
        strokeColor: "orange",
        strokeWidth: 10
      };
      return this.path.selected = true;
    };

    Chain.prototype.mouse_move = function(event) {
      var angle, current, i, next, vector, _i, _ref;
      this.segments[0].point = event.point;
      for (i = _i = 0, _ref = this.size - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        next = this.segments[i + 1];
        current = this.segments[i];
        angle = (current.point.subtract(next.point)).angle;
        vector = new paper.Point({
          angle: angle,
          length: 35
        });
        next.point = current.point.subtract(vector);
      }
      return this.path.smooth();
    };

    Chain.prototype.mouse_up = function(event) {
      this.path.style = this.style;
      return this.path.selected = false;
    };

    return Chain;

  })();
  return {
    Chain: Chain
  };
});
