// Generated by CoffeeScript 1.4.0
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

define(['paper'], function(paper) {
  var Chain;
  Chain = (function() {

    function Chain(canvas) {
      this.init = __bind(this.init, this);
      this.canvas = canvas;
      this.paper = new paper.PaperScope();
      this.paper.setup(this.canvas);
      this.path = new paper.Path();
      this.size = 25;
      this.segments = this.path.segments;
      this.path.style = {
        strokeColor: "blue",
        strokeWidth: 20,
        strokeCap: "round"
      };
      this.init();
    }

    Chain.prototype.init = function() {
      var i, start, _i, _ref;
      start = this.paper.view.center;
      for (i = _i = 0, _ref = this.size; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.path.add(new this.paper.Point(start.x + i * 10, start.y));
      }
      return this.paper.view.draw();
    };

    return Chain;

  })();
  return {
    Chain: Chain
  };
});
