// Generated by CoffeeScript 1.4.0

define(['paths'], function(paths) {
  var homepage;
  return homepage = function() {
    var canvas, drawing;
    canvas = document.getElementById("drawing_1");
    return drawing = new paths.drawing(canvas);
  };
});
