// Generated by CoffeeScript 1.4.0

define(['paths', 'test'], function(paths, test) {
  var homepage;
  return homepage = function() {
    var canvas, drawing;
    canvas = document.getElementById("drawing_1");
    drawing = new paths.drawing(canvas);
    return test.draw();
  };
});
