// Generated by CoffeeScript 1.4.0

define(['paths', 'chain'], function(paths, chain) {
  var homepage;
  return homepage = function() {
    var canvas, drawing, test;
    canvas = document.getElementById("drawing_2");
    drawing = new paths.drawing(canvas);
    return test = new chain.Chain($('#drawing_1')[0]);
  };
});
