// Generated by CoffeeScript 1.4.0

define(['paper'], function(paper) {
  var drawing;
  drawing = function(canvas) {
    var path, start;
    paper.setup(canvas);
    path = new paper.Path();
    path.strokeColor = "blue";
    start = new paper.Point(0, 0);
    path.moveTo(start);
    path.add(new paper.Point(25, 25));
    path.add(new paper.Point(50, 50));
    return paper.view.draw();
  };
  return {
    drawing: drawing
  };
});
